version: '3.8'

services:
  # Elasticsearch stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # dev only
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # Postgres DB
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auditdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Microservices
  audit-service:
    build: ./audit_service
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload
    ports:
      - "8005:8005"
    depends_on:
      - db

  api-gateway:
    build: ./api_gateway
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    depends_on:
      - audit-service

  billing-service:
    build: ./billing_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
    ports:
      - "8003:8003"
    depends_on:
      - audit-service

  user-service:
    build: ./user_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
    ports:
      - "8004:8004"
    depends_on:
      - audit-service

  risk-service-report:
    build: ./risk_service_report
    command: uvicorn app.main:app --host 0.0.0.0 --port 8006 --reload
    ports:
      - "8006:8006"
    depends_on:
      - audit-service

volumes:
  esdata:
  db-data:
